### ISSUE TITLE
Harmonization Error

### ISSUE THREAD

**Issue by jiangwenzong123** [tohinz/ConSinGAN#13]
Hi,when I want to run the instruction:
python main_train.py --gpu 1 --train_mode harmonization --train_stages 3 --min_size 120 --lrelu_alpha 0.3 --niter 1000 --batch_norm --input_name Images/Harmonization/scream.jpg
The following error occurred:

Traceback (most recent call last):
  File "main_train.py", line 111, in <module>
    train(opt)
  File "/home/lbd08/jwz/SA-ConSinGAN-master/ConSinGAN/training_harmonization_editing.py", line 75, in train
    naive_img, naive_img_large, fixed_noise,
UnboundLocalError: local variable 'naive_img_large' referenced before assignment

How can I solve it,thank you.

**Comment by tohinz** [comment]
Hi, this issue should have been resolved with Issue #2.
Can you do a `git pull` again to make sure you have the latest version?

**Comment by jiangwenzong123** [comment]
Thank you very much. It has been settled.
