### ISSUE TITLE
nan problem of SIFID calculation

### ISSUE THREAD

**Issue by SeibertronSS** [tohinz/ConSinGAN#14]
We would like to ask if you have encountered nan problems when calculating SIFID? My colleague and I cannot get the correct result when running the SIFID program given by SinGAN, the program gives a nan error.
The error message is as follows:
SIFID/sifid_score.py:262: RuntimeWarning: Mean of empty slice.
print('SIFID: ', sifid_values.mean())
../sinGAN/SinGAN-master/mypython/lib/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in true_divide
ret = ret.dtype.type(ret / rcount)
SIFID: nan

**Comment by tohinz** [comment]
Hi, I don't think we ever got that error. But if I remember correctly there were some issues about that in the SinGAN Github. Maybe check the (closed) issues there to see if you can find a solution.
