### ISSUE TITLE
How to generate images like SinGan？

### ISSUE THREAD

**Issue by dingyineversad** [tohinz/ConSinGAN#16]
Sorry, I don't quite understand. What command do you input to generate the image?How do you determine the scale of the generated image?
Thank you very much！

**Comment by tohinz** [comment]
Please see [here](https://github.com/tohinz/ConSinGAN#sample-more-images) for how to sample from the model (this will automatically sample in different scales).
You can train like [this](https://github.com/tohinz/ConSinGAN#unconditional-generation-arbitrary-sizes) specifically to train for rescaling later and then sample as before.
You can manually change the scale in the code [here](https://github.com/tohinz/ConSinGAN/blob/8b4681fc47796dacf0b229e50214b2c36fec860b/evaluate_model.py#L85) by changing `scale_w` and `scale_h`.

**Comment by dingyineversad** [comment]
@tohinz OK, I see. Thank you very much
