### ISSUE TITLE
train a default harmonization model ERROR

### ISSUE THREAD

**Issue by yazheng0307** [tohinz/ConSinGAN#5]
I try to run the code in README:

python main_train.py --gpu 0 --train_mode harmonization --train_stages 3 --min_size 120 --lrelu_alpha 0.3 --niter 1000 --batch_norm --input_name Images/Harmonization/scream.jpg

It shows the message:

Traceback (most recent call last):   File "main_train.py", line 111, in <module>     train(opt)   File "/root/code/ConSinGAN/ConSinGAN/training_harmonization_editing.py", line 76, in train     naive_img, naive_img_large, fixed_noise, 
**UnboundLocalError: local variable 'naive_img_large' referenced before assignment**

Can you tell me how to solve this problem?Thank YOU!

**Comment by tohinz** [comment]
Hi, this was fixed in Issue #2 (yesterday), so if you do a new git pull it should work.

**Comment by yazheng0307** [comment]
> Hi, this was fixed in Issue #2 (yesterday), so if you do a new git pull it should work.


> Hi, this was fixed in Issue #2 (yesterday), so if you do a new git pull it should work.

It works.Thank you!
