### ISSUE TITLE
Is there a way to save ConSinGAN model training progress?

### ISSUE THREAD

**Issue by deltaraindream** [tohinz/ConSinGAN#7]
Hi! Is there a way to save and to load the process of model training? For example, I use google colab for a faster model training, but maybe 30% of time the process interrupts , and I should start from the beginning again.

**Comment by tohinz** [comment]
Hi, the networks are saved after each stage (see e.g. [line 99 in training_generation.py](https://github.com/tohinz/ConSinGAN/blob/3114478d4dee7bd62a76cdfe8e7f51b41a7a57a0/ConSinGAN/training_generation.py#L199)). You could of course potentially store them more often. To restart from there you'll also have to save noise_amp (see [here](https://github.com/tohinz/ConSinGAN/blob/3114478d4dee7bd62a76cdfe8e7f51b41a7a57a0/ConSinGAN/training_generation.py#L53)).

To resume training you can simply load the saved models (see e.g. in [evaluate_model.py](https://github.com/tohinz/ConSinGAN/blob/3114478d4dee7bd62a76cdfe8e7f51b41a7a57a0/evaluate_model.py#L68) how to do this) and then continue training from there.
